error id: jpfUyJV5waxyBJ3MswwTmQ==
### Bloop error:

at scala.Main$.scala$Main$$anon$3$$_$_$$anonfun$1(Main.scala:52)
#### Short summary: 

at scala.Main$.scala$Main$$anon$3$$_$_$$anonfun$1(Main.scala:52)